name: Build and Release

on:
  push:
    branches:
      - main
      - fix-build

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
          registry-url: https://registry.npmjs.org/

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install ldid
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev libplist-dev
          git clone https://github.com/sbingner/ldid.git
          make -C ldid
          sudo cp -f ./ldid/ldid /usr/local/bin/

      - name: Build the project
        run: npm run build

      - name: Build binaries with pkg
        run: npm run build:binaries
